---
apiVersion: v1
kind: Namespace
metadata:
  name: test-elasticsearch
  labels:
    name: test-elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
  namespace: test-elasticsearch
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30079
    protocol: TCP
  selector:
    name: redis-master

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  namespace: test-elasticsearch
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      name: redis-master
      labels:
        name: redis-master
    spec:
      containers:
      - name: redis-master
        image: kubeguide/redis-master
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
  labels:
    name: redis-slave
  namespace: test-elasticsearch
spec:
  replicas: 2
  selector:
    name: redis-slave
  template:
    metadata:
      labels:
        name: redis-slave
    spec:
      containers:
      - name: slave
        image: kubeguide/guestbook-redis-slave
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-slave
  namespace: test-elasticsearch
spec:
  ports:
  - port: 6379
  selector:
    name: redis-slave
